# [NA dan default type]
# Ketik nilai NA
NA
# Tampilkan type dari NA dengan function typeof
typeof(NA)
```

# [Menggunakan function is.na]
# Buat variable x yang diisi dengan nilai NA
x <- NA
# Pengecekan variable x dengan nilai NA menggunakan operator ==
x == NA
# Pengecekan variable x dengan nilai NA menggunakan function is.na
is.na(x)
```

# [Variasi NA dan is.na]
typeof(NA_integer_)
typeof(NA_real_)
typeof(NA_complex_)
typeof(NA_character_)
is.na(NA_integer_)
is.na(NA_real_)
is.na(NA_complex_)
is.na(NA_character_)

# [Coercion pada Vector yang mengandung NA]
# Membuat vector bernama isi.vector dengan isi bilangan, dimana salah satunya memiliki missing value
isi.vector <- c(1,2,3,NA,3,1)
# Mengecek keseluruhan tipe data dengan perulangan lapply dan typeof
lapply(isi.vector, typeof)
# Menggunakan is.na untuk mengecek keberadaan missing value dari tiap elemen pada vector 
is.na(isi.vector)
```

# [NULL dan Vector]
# Membuat vector dengan 7 elemen termasuk NA dan NULL
isi.vector <- c(1, 2, 3, NA, 5, NULL, 7)
# Menghitung jumlah elemen dari isi.vector
length(isi.vector)
```

# [NULL dan List]
#Membuat list dengan 3 elemen termasuk NA dan NULL 
isi.list <-  list(1, NULL, 3, NA, 5)
#Menghitung jumlah elemen dari isi.list
length(isi.list)
```

# [nf untuk mewakili Infinite Number]

# Hitung kalkulasi 5 dibagi dengan 0
5/0 
# Hitung kalkulasi -120 dibagi dengan 0
 -120/0
```

# [NaN (Not a Number)
# Hitung kalkulasi 0 dibagi dengan 0
0/0
```

# [NaN dari hasil function log()]

# Hitung logaritma dari angka -1000
log(-1000)
```

# [Fungsi is.nan]
# Buat variable contoh.nan
contoh.nan <- 0/0
# Periksa dengan function is.nan
is.nan(contoh.nan)
```

# [NaN dan is.na versus NA dan is.nan]
# Masukkan code di bawah ini sesuai permintaan soal
is.na(NaN)
is.nan(NA)
```

# [Menghitung Jumlah Missing Values dari satu Vector]
# Masukkan code di bawah ini sesuai permintaan soal
isi.vector <- c(1,2,NA,4,5,NaN,6)
sum(is.na(isi.vector) == TRUE)
```

# [Membuat Factor di R]
# Buatlah factor dengan isi nilai teks "Jan", "Feb", dan "Mar"
factor(c("Jan","Feb","Mar"))
```

# [Atribut levels dan class pada Factor]
# Variable factor bernama faktor.bulan dengan nilai teks "Jan", "Feb", dan "Mar"
faktor.bulan <- factor(c("Jan","Feb","Mar"))
attributes(faktor.bulan)
```

# [Function levels dan class pada Factor]
# Variable factor bernama faktor.bulan dengan nilai teks "Jan", "Feb", dan "Mar"
faktor.bulan <- factor(c("Jan","Feb","Mar"))
levels(faktor.bulan)
class(faktor.bulan)
```

# [Perulangan Nilai pada Factor]
# Buatlah factor dengan teks "Jan", "Feb", "Mar","Jan","Mar", dan "Jan"
factor(c("Jan","Feb","Mar","Jan","Mar","Jan"))
```

# [Penggunaan as.integer pada Factor]
# Buatlah factor dengan teks "Jan", "Feb", "Mar","Jan","Mar", dan "Jan"
factor.bulan <- factor(c("Jan","Feb","Mar","Jan","Mar","Jan"))
as.integer(factor.bulan)
```

# [Mengganti "Jan" menjadi "Januari"]
# Buatlah factor dengan teks "Jan", "Feb", "Mar","Jan","Mar", dan "Jan"
factor.bulan <- factor(c("Jan","Feb","Mar","Jan","Mar","Jan"))
# Mengganti levels 
levels(factor.bulan)[2] <- "Januari"
levels(factor.bulan)[3] <- "Maret"
factor.bulan
```

# [Angka sebagai Kategori]
# Buatlah factor bernama factor.umur dengan isi c(12, 35, 24, 12, 35, 37)
factor.umur <- factor(c(12, 35, 24, 12, 35, 37))
# Tampilkan variable factor.umur 
factor.umur
```

# [NA, NaN, NULL pada saat pembentukan Factor]
# Buatlah variable factor.lokasi dengan isi berupa vector 
# c("Bandung", "Jakarta", NA, "Jakarta", NaN, "Medan", NULL, NULL, "Bandung") 
factor.lokasi <- factor(c("Bandung", "Jakarta", NA, "Jakarta", NaN, "Medan", NULL, NULL, "Bandung"))
# Tampilkan factor.lokasi
factor.lokasi
```

# [Menghitung panjang Factor dengan length]
# Buatlah variable factor.lokasi dengan isi berupa vector 
# c("Bandung", "Jakarta", NA, "Jakarta", NaN, "Medan", NULL, NULL, "Bandung") 
factor.lokasi <- factor(c("Bandung", "Jakarta", NA, "Jakarta", NaN, "Medan", NULL, NULL, "Bandung"))
# Tampilkan panjang dari variable factor.lokasi
length(factor.lokasi)
```

# [Menyusun levels dari awal]
# Variable factor dengan isi vector c("Jan","Feb","Mar","Jan","Mar") 
factor(c("Jan","Feb","Mar","Jan","Mar"), levels = c("Jan","Feb","Mar"))
```

# [Dataset Kependudukan Jakarta](https://academy.dqlab.id/main/livecode/12/46/307)
 
```

# [Membaca Dataset CSV]
# Membaca dataset dengan read.csv dan dimasukkan ke variable penduduk.dki
penduduk.dki <- read.csv("https://academy.dqlab.id/dataset/dkikepadatankelurahan2013.csv", sep=",")
penduduk.dki
```

# [Profile Dataset dengan Function str]
# Membaca dataset dengan read.csv dan dimasukkan ke variable penduduk.dki
penduduk.dki <- read.csv("https://academy.dqlab.id/dataset/dkikepadatankelurahan2013.csv", sep=",")
str(penduduk.dki)
```

# [Profile Dataset dengan Function summary]
# Membaca dataset dengan read.csv dan dimasukkan ke variable penduduk.dki
penduduk.dki <- read.csv("https://academy.dqlab.id/dataset/dkikepadatankelurahan2013.csv", sep=",")
summary(penduduk.dki)
```

# [Menggunakan argumen check.names = FALSE]
# Membaca dataset dengan read.csv dan dimasukkan ke variable penduduk.dki
penduduk.dki <- read.csv("https://academy.dqlab.id/dataset/dkikepadatankelurahan2013.csv", sep=",", 
                         check.names = FALSE)
str(penduduk.dki)
```

# [Membaca Tab Separated Value (TSV)]
# Membaca dataset dengan read.csv dan dimasukkan ke variable penduduk.dki
penduduk.dki <- read.csv("https://academy.dqlab.id/dataset/dkikepadatankelurahan2013.tsv", sep="\t")
penduduk.dki
```

# [Membaca Dataset File Excel dengan read.xlsx]
library(openxlsx)
# Membaca dataset dengan read.xlsx dan dimasukkan ke variable penduduk.dki
penduduk.dki.xlsx <- read.xlsx(xlsxFile="https://academy.dqlab.id/dataset/dkikepadatankelurahan2013.xlsx")
str(penduduk.dki.xlsx)
```

# [Function names]
# Membaca dataset csv
penduduk.dki.csv <-read.csv("https://academy.dqlab.id/dataset/dkikepadatankelurahan2013.csv", sep=",")
# Menggunakan names untuk variable penduduk.dki.csv
names(penduduk.dki.csv)
```

# [Merubah Satu Nama Kolom]
# Membaca dataset csv
penduduk.dki.csv <-read.csv("https://academy.dqlab.id/dataset/dkikepadatankelurahan2013.csv", sep=",")
names(penduduk.dki.csv)[1] <- "PERIODE"
names(penduduk.dki.csv)[2] <- "PROPINSI"
names(penduduk.dki.csv)
```

# [Merubah Sejumlah Nama Kolom]
# Membaca dataset csv
penduduk.dki.csv <-read.csv("https://academy.dqlab.id/dataset/dkikepadatankelurahan2013.csv", sep=",")
names(penduduk.dki.csv)[c(1:2)] <- c("PERIODE", "PROPINSI")
names(penduduk.dki.csv)
```

# [Membuang Kolom dengan Bantuan Operator %in%]
#Membaca dataset csv
penduduk.dki.csv <-read.csv("https://academy.dqlab.id/dataset/dkikepadatankelurahan2013.csv", sep=",")
#Membuang kolom X, X.1, X.2 s/d X.11
penduduk.dki.csv <- penduduk.dki.csv[,!names(penduduk.dki.csv) %in%
                                       c("X","X.1","X.2","X.3","X.4","X.5","X.6",
                                         "X.7","X.8","X.9","X.10", "X.11")]
names(penduduk.dki.csv)
```
# [Merubah Tipe Kolom menjadi Factor]
library(openxlsx)
# Membaca dataset dengan read.xlsx dan dimasukkan ke variable penduduk.dki
penduduk.dki.xlsx <- read.xlsx(xlsxFile="https://academy.dqlab.id/dataset/dkikepadatankelurahan2013.xlsx")
penduduk.dki.xlsx$NAMA.PROVINSI <-as.factor(penduduk.dki.xlsx$NAMA.PROVINSI)
str(penduduk.dki.xlsx)
```

# [Mengambil Kolom Laki.Laki / Perempuan dengan grep]
library(openxlsx)
penduduk.dki.xlsx <- read.xlsx(xlsxFile="https://academy.dqlab.id/dataset/dkikepadatankelurahan2013.xlsx")
# Tampilkan nama-nama kolom yang mengandung kata "perempuan".
pola_nama_perempuan <- grep(pattern="perempuan", x = names(penduduk.dki.xlsx), ignore.case=TRUE)
names(penduduk.dki.xlsx[pola_nama_perempuan])
# Tampilkan nama-nama kolom yang mengandung kata "laki-laki"
pola_nama_laki_laki <- grep(pattern="laki-laki", x = names(penduduk.dki.xlsx), ignore.case=TRUE)
names(penduduk.dki.xlsx[pola_nama_laki_laki])
```

# [Menambahkan kolom Penjumlahan](
library(openxlsx)
penduduk.dki.xlsx <- read.xlsx(xlsxFile="https://academy.dqlab.id/dataset/dkikepadatankelurahan2013.xlsx")
# Tampilkan nama-nama kolom yang mengandung kata "perempuan".
pola_nama_perempuan <- grep(pattern="perempuan", x = names(penduduk.dki.xlsx), ignore.case=TRUE)
penduduk.dki.xlsx$PEREMPUAN35TAHUNKEATAS  <- rowSums(penduduk.dki.xlsx[pola_nama_perempuan])
```

# [Normalisasi Data dari Kolom ke Baris]
library(openxlsx)
library(reshape2)
penduduk.dki.xlsx <- read.xlsx(xlsxFile="https://academy.dqlab.id/dataset/dkikepadatankelurahan2013.xlsx")
# Transformasi kolom dataset penduduk.dki.xlsx, disimpan ke variable penduduk.dki.transform
penduduk.dki.transform <- melt(data=penduduk.dki.xlsx, 
                               id.vars=c( "NAMA.KECAMATAN", "NAMA.KELURAHAN"), 
                               measure.vars = c("35-39.Laki-Laki", "35-39.Perempuan"), 
                               variable.name = "DEMOGRAFIK", 
                               value.name="JUMLAH")
# Menampilkan variable penduduk.dki.transform
penduduk.dki.transform
```

# [Split Fields]
library(openxlsx)
library(reshape2)
penduduk.dki.xlsx <- read.xlsx(xlsxFile="https://academy.dqlab.id/dataset/dkikepadatankelurahan2013.xlsx")
penduduk.dki.transform <- melt(data=penduduk.dki.xlsx, 
                               id.vars=c( "NAMA.KECAMATAN", "NAMA.KELURAHAN"), 
                               measure.vars = c("35-39.Laki-Laki", "35-39.Perempuan"), 
                               variable.name = "DEMOGRAFIK", 
                               value.name="JUMLAH") 
# Memecah isi kolom DEMOGRAFIK menjadi "RENTANG.UMUR" dan "JENIS.KELAMIN"
penduduk.dki.transform[c("RENTANG.UMUR", "JENIS.KELAMIN")] <- colsplit(penduduk.dki.transform$DEMOGRAFIK,"\\.",c("RENTANG.UMUR","JENIS.KELAMIN"))
penduduk.dki.transform$DEMOGRAFIK <- NULL
penduduk.dki.transform
